### ISSUE TITLE
Video in format .m3u8 and .ts

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [inthehand/InTheHand.Forms#48]
How to play video in format .m3u8 and .ts?
It is most important for me the function, because my project run videos in this format.
Sorry my bad english, im from brazil.

**Comment by peterfoot** [comment]
The control will only play natively supported file formats on each platform. For m3u and m3u8 files the control won't open these directly as they are playlists rather than media however you should be able to parse the text yourself and play each file in sequence. I'm not sure how widely .ts is supported.
