### ISSUE TITLE
Video player doesnt work for UWP with Compile with .NET Native tool chain turned on

### ISSUE THREAD

**Issue by nitrouscutter** [inthehand/InTheHand.Forms#55]
I dont know why the video player wont work when turning on "Compile with .NET Native tool chain" flag in project build properties. Usually places want this flag checked to improve speed and performance when submitting to the store for final version. Any suggestions on how to make the player work with this flag checked?

**Comment by nitrouscutter** [comment]
@peterfoot Also thank you this is a pretty sweet player

**Comment by peterfoot** [comment]
Hi, thanks for your feedback. I believe it is an issue where we need to add an additional entry to the "Runtime Directives" file to tell the .NET Native Tools not to strip out the platform specific code - the renderer is not called directly so it is probably not identified as actually used in the app. In your Properties folder in the UWP project you should have a Default.rd.xml or similar and you can add the following line after the default Application assembly:-
    
    
    
    <Assembly Name="InTheHand.Forms.Platform.UWP" Serialize="Required Public"/>

I haven't fully tested this yet but I need to add it to the sample project and document it more clearly.

**Comment by nitrouscutter** [comment]
I tried adding that assembly and it didnt seem to work. Must be something else needed with it.

**Comment by nitrouscutter** [comment]
I might have found a solution Mr. @peterfoot. I added `typeof(InTheHand.Forms.Platform.UWP.ButtonLineBreakModeEffect).GetTypeInfo().Assembly`

to the assembly list in the App.xaml.bs file within the UWP project. It seemed to run the videos on UWP with compile native on. Now to test in the store

**Comment by peterfoot** [comment]
There is another option using an overload of Forms.Init:-

// For .NET Native compilation, you have to tell Xamarin.Forms which assemblies it should scan for custom controls and renderers var rendererAssemblies = new[] { typeof(InTheHand.Forms.Platform.UWP.ButtonLineBreakModeEffect).GetTypeInfo().Assembly }; 

Xamarin.Forms.Forms.Init(e, rendererAssemblies);

(you can use any of the types in the platform assembly instead of ButtonLineBreakModeEffect but you only need one entry per assembly).

I'll add this to the documentation.
